services:
  azurefunction:
    container_name: "IVNT-AzureFunctionApp"
    image: mcr.microsoft.com/azure-functions/powershell:4-powershell7.2
    ports:
      - "8080:80"
    environment:
      - AzureWebJobsScriptRoot=/home/site/wwwroot
      - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
      - FUNCTIONS_WORKER_RUNTIME=powershell
      - FUNCTIONS_WORKER_RUNTIME_VERSION:7.2
      - AzureFunctionsJobHost__Logging__Console__IsEnabled=true
      - WEBSITE_HOSTNAME=127.0.0.1:8080
    volumes:
      - ./:/home/site/wwwroot
    networks:
      - afnetwork
    depends_on:
      - azurite

  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    container_name: "IVNT-Azurite"
    hostname: azurite
    restart: unless-stopped
    expose:
      - "10000"
      - "10001"
      - "10002"
    networks:
      - afnetwork

  
  durablefunctionsmonitor:
    ports:
        - 7072:80
    environment:
        - AzureWebJobsStorage=DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://azurite:10000/devstoreaccount1;QueueEndpoint=http://azurite:10001/devstoreaccount1;TableEndpoint=http://azurite:10002/devstoreaccount1;
        - DFM_NONCE=i_sure_know_what_i_am_doing
    image: scaletone/durablefunctionsmonitor:6.5
    container_name: "IVNT-DurableFunctionsMonitor"
    networks:
      - afnetwork

networks:
  afnetwork:
    name: afnetwork-standalone
    driver: bridge
